### ISSUE TITLE
Doubled entries for OSX

### ISSUE THREAD

**Issue by popadrianc** [Akhliskun/taskcluster-worker-checker#130]
**ISSUE :** doubled entries only for osx machines
**When:** this happens when running  

> python client.py -v -l 2 or python client.py -v -l 1 ... etc
and at the menu, selecting : 
> 11
This doesn't occurs on menu selection : 14

**Comment by Akhliskun** [comment]
This was been fixed by commit d1ac456ce19483aa35dadd2a17141ebb34cb839d
