### ISSUE TITLE
Grab machines from ServiceNow

### ISSUE THREAD

**Issue by Akhliskun** [Akhliskun/taskcluster-worker-checker#2]
Currently we are generating a hard-coded list based on ranges that could change at any time!
We should be using Mozilla's ServiceNow API and grab all the machines we are interested on.

**What to pay attention to**:
- The "magic" where we set() our 2 diffs expects a list with the machine name as: t-linux64-ms-280
- We print a quick ssh command and do MDC logic based on generate_machine_lists(workertype) -> global mdc1,mdc2. We don't want to break this, but we can also look at better ways to handle this.

**Comment by bccrisan** [comment]
https://developer.servicenow.com/app.do#!/rest_api_doc?v=jakarta&id=r_TableAPI-POST
This might help with the issue, tried and debugged the example they offer using our service now, got response 200 but got a bunch of errors after that.

**Comment by Akhliskun** [comment]
This issues will not be possible, as Moz needs to pay for API services.
Will close the issue for now
