### ISSUE TITLE
Fix MacOSX ssh command.

### ISSUE THREAD

**Issue by Akhliskun** [Akhliskun/taskcluster-worker-checker#5]
In the logic at [line168](https://github.com/Akhliskun/taskcluster-worker-checker/blob/master/client.py#L168) we generate the FQDN wrong.

**Current Output**:
`ssh LDAP@MACHINE.releng.DATACENTER.mozilla.com`

**Expected Output**:
`ssh LDAP@MACHINE.test.releng.DATACENTER.mozilla.com`

**Comment by bccrisan** [comment]
also the datacenter is wrong, MDC1 is reversed with MDC2 thus, generating a wrong FQDN, again.

**Comment by mutterroland** [comment]
@bccrisan fixed that. I was working on OSX today and saw that's happening.

**Comment by Akhliskun** [comment]
This issue has been fixed for a couple of days.
