### ISSUE TITLE
Make the script use the correct DC lists

### ISSUE THREAD

**Issue by bccrisan** [Akhliskun/taskcluster-worker-checker#70]
While trying to modify the script to accept the new machines, I observed that atm we are using "mdc2_range" from linux to windows thus, providing misleading information.

Use case:
 print("Total of missing server : {}".format(len(missing_machines) - len(mdc2_range)))

I also tried to correct this but for some reason, the "mdc_range" from generating windows it's not accessible.

**Comment by Akhliskun** [comment]
This was fixed long time ago, but forgot to close the issue.
