### ISSUE TITLE
Over-engineered expression

### ISSUE THREAD

**Issue by bccrisan** [Akhliskun/taskcluster-worker-checker#9]
doing this:
python3 client.py -w WORKER_TYPE -u LDAP_USERNAME | cat >> missing.txt

can be replaced with:
python3 client.py -w WORKER_TYPE -u LDAP_USERNAME > missing.txt

The use of "| cat >>" is a bit over-engineered.

**Comment by Akhliskun** [comment]
Pull Request the change please 💯

**Comment by Akhliskun** [comment]
Issue closed with commit 9e6f3bd
